{
 "title": "My Chats",
 "time": { "from": "now-12y", "to": "now" },
 "panels": [
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tg_bytes_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total bytes per chat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum by(file) (tg_bytes_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LOL total per chat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(file) (tg_expressions_total{expression=\"(?i)lol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOL rate per chat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum by(file) (rate(tg_expressions_total{expression=\"(?i)lol\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}